<a href="https://colab.research.google.com/github/kiselpd/HW5_ML/blob/main/price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#for my GoogleDisk
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/GoogleColab/HW5

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/GoogleColab/HW5


In [311]:
%matplotlib inline
import pandas as pd
import numpy as np

In [312]:
train_df = pd.read_csv('Train.csv')
test_df = pd.read_csv('Test.csv')

In [313]:
import datetime as dt
train_df["date"] = pd.to_datetime(train_df["date"]).map(dt.datetime.toordinal)
test_df["date"] = pd.to_datetime(test_df["date"]).map(dt.datetime.toordinal)

In [314]:
from sklearn.model_selection import train_test_split

In [315]:
id = test_df["id"]
id

0        100000
1        100001
2        100002
3        100003
4        100004
          ...  
99995    199995
99996    199996
99997    199997
99998    199998
99999    199999
Name: id, Length: 100000, dtype: int64

In [316]:
train_df = train_df.drop(columns = ["id"])
test_df = test_df.drop(columns = ["id"])

In [319]:
X, y = train_test_split(train_df, test_size=0.3, random_state=42)

In [320]:
from sklearn.impute import KNNImputer

In [322]:
imputer = KNNImputer(n_neighbors = 10)
X = imputer.fit_transform(X)
y = imputer.fit_transform(y)

In [323]:
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [324]:
X = pd.DataFrame(X, columns = train_df.columns)
y = pd.DataFrame(y, columns = train_df.columns)

In [325]:
y_train = X["price"]
X_train = X.drop(columns = ["price"])

In [326]:
y_test = y["price"]
X_test = y.drop(columns = ["price"])

In [327]:
X_train

date  street_id  build_tech  floor  area  rooms  balcon  \
0      734777.0      280.0         0.0    4.0  59.0    3.0     0.0   
1      734350.0       71.0         0.0    9.0  48.0    2.0     0.0   
2      734169.0      239.0         1.0   11.0  95.0    3.0     1.0   
3      734319.0      594.0         0.0    2.0  34.0    1.0     0.0   
4      734381.0      545.0         1.0    9.0  52.0    2.0     1.0   
...         ...        ...         ...    ...   ...    ...     ...   
69995  734411.0      259.0         1.0    5.0  60.0    3.0     1.0   
69996  734319.0      283.0         1.0   10.0  60.0    3.0     1.0   
69997  734777.0       18.0         1.0    2.0  60.0    3.0     1.0   
69998  734138.0      283.0         1.0    1.0  60.0    3.0     0.0   
69999  734442.0      517.0         0.0    6.0  34.0    1.0     0.0   

       metro_dist  g_lift  n_photos  kw1  kw2  kw3  kw4  kw5  kw6  kw7  kw8  \
0            10.0     0.6       4.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
1             5.0     0.0       2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2            25.0     1.0       1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3            20.0     0.5       2.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
4             5.0     0.7       3.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
...           ...     ...       ...  ...  ...  ...  ...  ...  ...  ...  ...   
69995        30.0     0.0       7.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
69996        20.0     0.5       4.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
69997        30.0     1.0       3.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
69998        25.0     1.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
69999        10.0     0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       kw9  kw10  kw11  kw12  kw13  
0      0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...  
69995  0.0   0.0   0.0   0.0   0.0  
69996  0.0   0.0   0.0   0.0   0.0  
69997  0.0   0.0   0.0   0.0   0.0  
69998  0.0   0.0   0.0   0.0   0.0  
69999  0.0   0.0   0.0   0.0   0.0  

[70000 rows x 23 columns]

In [328]:
y_train

0        5021000.0
1        3880000.0
2        7550000.0
3        1126000.0
4        5054000.0
           ...    
69995    5023000.0
69996    5636000.0
69997    2957000.0
69998    4913000.0
69999    5330000.0
Name: price, Length: 70000, dtype: float64

In [329]:
X_train

date  street_id  build_tech  floor  area  rooms  balcon  \
0      734777.0      280.0         0.0    4.0  59.0    3.0     0.0   
1      734350.0       71.0         0.0    9.0  48.0    2.0     0.0   
2      734169.0      239.0         1.0   11.0  95.0    3.0     1.0   
3      734319.0      594.0         0.0    2.0  34.0    1.0     0.0   
4      734381.0      545.0         1.0    9.0  52.0    2.0     1.0   
...         ...        ...         ...    ...   ...    ...     ...   
69995  734411.0      259.0         1.0    5.0  60.0    3.0     1.0   
69996  734319.0      283.0         1.0   10.0  60.0    3.0     1.0   
69997  734777.0       18.0         1.0    2.0  60.0    3.0     1.0   
69998  734138.0      283.0         1.0    1.0  60.0    3.0     0.0   
69999  734442.0      517.0         0.0    6.0  34.0    1.0     0.0   

       metro_dist  g_lift  n_photos  kw1  kw2  kw3  kw4  kw5  kw6  kw7  kw8  \
0            10.0     0.6       4.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
1             5.0     0.0       2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2            25.0     1.0       1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3            20.0     0.5       2.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
4             5.0     0.7       3.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
...           ...     ...       ...  ...  ...  ...  ...  ...  ...  ...  ...   
69995        30.0     0.0       7.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
69996        20.0     0.5       4.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
69997        30.0     1.0       3.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
69998        25.0     1.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
69999        10.0     0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       kw9  kw10  kw11  kw12  kw13  
0      0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...  
69995  0.0   0.0   0.0   0.0   0.0  
69996  0.0   0.0   0.0   0.0   0.0  
69997  0.0   0.0   0.0   0.0   0.0  
69998  0.0   0.0   0.0   0.0   0.0  
69999  0.0   0.0   0.0   0.0   0.0  

[70000 rows x 23 columns]

In [458]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor

In [469]:
RFR = RandomForestRegressor(n_estimators = 200, min_samples_split = 4)
RFR.fit(X_train, y_train)

RFR_pred = RFR.predict(X_test)

In [470]:
mean_absolute_error(y_test, RFR_pred)

1603020.3674433967

In [408]:
LiR = LinearRegression()
LiR.fit(X_train, y_train)

LiR_pred = LiR.predict(X_test)

In [409]:
LiR_pred

array([6955274.9268024 , 3650617.34617352, 3834578.63064957, ...,
       5838619.45145583, 2288646.20488477, 5483297.78126764])

In [410]:
mean_absolute_error(y_test, LiR_pred)

1800844.784062263

In [411]:
#GBR = GradientBoostingRegressor()
#BR.fit(X_train, y_train.ravel())

#GBR_pred = GBR.predict(X_test)

In [412]:
#GBR_pred

In [413]:
#mean_absolute_error(y_test, GBR_pred)

In [414]:
RD = Ridge()
RD.fit(X_train, y_train.ravel())

RD_pred = RD.predict(X_test)

In [415]:
RD_pred

array([6955147.53443575, 3650612.05250692, 3834591.10117865, ...,
       5838608.42077589, 2288737.86124563, 5483181.96409798])

In [416]:
mean_absolute_error(y_test, RD_pred)

1800843.1796128554

In [417]:
L = Lasso()
L.fit(X_train, y_train.ravel())

L_pred = L.predict(X_test)

In [418]:
L_pred

array([6955267.24130034, 3650621.57874894, 3834566.59922624, ...,
       5838609.8945415 , 2288655.25863695, 5483291.03501868])

In [419]:
mean_absolute_error(y_test, L_pred)

1800845.2177311277

In [471]:
stack = np.hstack([LiR_pred.reshape(-1, 1), L_pred.reshape(-1, 1), RD_pred.reshape(-1, 1), RFR_pred.reshape(-1, 1)])
stack

array([[6955274.9268024 , 6955267.24130034, 6955147.53443575,
        6074426.48809524],
       [3650617.34617352, 3650621.57874894, 3650612.05250692,
        2970524.64087302],
       [3834578.63064957, 3834566.59922624, 3834591.10117865,
        2246084.54166667],
       ...,
       [5838619.45145583, 5838609.8945415 , 5838608.42077589,
        6240248.98015873],
       [2288646.20488477, 2288655.25863695, 2288737.86124563,
        3497058.64285714],
       [5483297.78126764, 5483291.03501868, 5483181.96409798,
        4362697.0297619 ]])

In [472]:
y_test

0         5651000.0
1         1321000.0
2         2250000.0
3         2539000.0
4         2396000.0
            ...    
29995    10268000.0
29996     1444000.0
29997    10117000.0
29998     2603000.0
29999     1000000.0
Name: price, Length: 30000, dtype: float64

In [473]:
test_stack = np.hstack([X_test, stack])
test_stack

array([[7.34777000e+05, 3.45000000e+02, 1.00000000e+00, ...,
        6.95526724e+06, 6.95514753e+06, 6.07442649e+06],
       [7.34808000e+05, 3.97000000e+02, 0.00000000e+00, ...,
        3.65062158e+06, 3.65061205e+06, 2.97052464e+06],
       [7.34472000e+05, 5.88000000e+02, 1.00000000e-01, ...,
        3.83456660e+06, 3.83459110e+06, 2.24608454e+06],
       ...,
       [7.34289000e+05, 4.74000000e+02, 1.00000000e+00, ...,
        5.83860989e+06, 5.83860842e+06, 6.24024898e+06],
       [7.34381000e+05, 4.81000000e+02, 0.00000000e+00, ...,
        2.28865526e+06, 2.28873786e+06, 3.49705864e+06],
       [7.34228000e+05, 2.10000000e+02, 1.00000000e+00, ...,
        5.48329104e+06, 5.48318196e+06, 4.36269703e+06]])

In [ ]:
#GBR = GradientBoostingRegressor()
#BR.fit(X_train, y_train.ravel())

#GBR_pred = GBR.predict(X_test)

In [474]:
GBR_stack = GradientBoostingRegressor(n_estimators = 100)
GBR_stack.fit(test_stack, y_test.ravel())

GradientBoostingRegressor()

In [475]:
test_df

date  street_id  build_tech  floor  area  rooms  balcon  \
0      734563.0      459.0         0.6    1.0  60.0    3.0     1.0   
1      734563.0      344.0         1.0   10.0  52.0    2.0     1.0   
2      734563.0      585.0         0.0    4.0  54.0    3.0     0.0   
3      734563.0      494.0         0.7    2.0  52.0    2.0     1.0   
4      734563.0      622.0         1.0    9.0  60.0    3.0     1.0   
...         ...        ...         ...    ...   ...    ...     ...   
99995  735112.0      613.0         1.0    2.0  34.0    1.0     1.0   
99996  735112.0      167.0         1.0   10.0  61.0    3.0     1.0   
99997  735112.0      391.0         1.0    9.0  34.0    1.0     1.0   
99998  735112.0       21.0         0.0    7.0  58.0    3.0     0.0   
99999  735112.0      409.0         0.0   11.0  33.0    1.0     0.0   

       metro_dist  g_lift  n_photos  kw1  kw2  kw3  kw4  kw5  kw6  kw7  kw8  \
0            30.0     0.0       4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1            21.0     0.6       4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2            30.0     0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3            25.0     1.0       3.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
4            15.0     0.8       1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
...           ...     ...       ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995        25.0     0.3       2.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
99996        30.0     0.6       4.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
99997        30.0     0.5       3.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
99998        30.0     0.0       3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99999        24.5     0.0       1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       kw9  kw10  kw11  kw12  kw13  
0      0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...  
99995  0.0   0.0   0.0   0.0   0.0  
99996  0.0   0.0   0.0   0.0   0.0  
99997  0.0   0.0   0.0   0.0   0.0  
99998  0.0   0.0   0.0   0.0   0.0  
99999  0.0   0.0   0.0   0.0   0.0  

[100000 rows x 23 columns]

In [425]:
test_df = imputer.fit_transform(test_df)


In [426]:
test_df

array([[7.34563e+05, 4.59000e+02, 6.00000e-01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [7.34563e+05, 3.44000e+02, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [7.34563e+05, 5.85000e+02, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [7.35112e+05, 3.91000e+02, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [7.35112e+05, 2.10000e+01, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [7.35112e+05, 4.09000e+02, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00]])

In [433]:
test_df = pd.DataFrame(test_df, columns = X_test.columns)

In [434]:
LiR_test_pred = LiR.predict(test_df)

In [435]:
L_test_pred = L.predict(test_df)

In [436]:
RD_test_pred = RD.predict(test_df)

In [476]:
RFR_test_pred = RFR.predict(test_df)

In [477]:
test_stack = np.hstack([test_df, LiR_test_pred.reshape(-1, 1), L_test_pred.reshape(-1, 1), RD_test_pred.reshape(-1, 1), RFR_test_pred.reshape(-1, 1)])
test_stack.shape

(100000, 27)

In [478]:
final_pred = GBR_stack.predict(test_stack)

In [481]:
final_pred

array([6396485.28301786, 6166259.85865376, 2410517.14236038, ...,
       4338132.76087263, 3935493.18159639, 3139021.65617539])

In [482]:
result = np.hstack([(id.to_numpy()).reshape(-1, 1), final_pred.reshape(-1, 1)])

In [483]:
result.astype(np.int32)

array([[ 100000, 6396485],
       [ 100001, 6166259],
       [ 100002, 2410517],
       ...,
       [ 199997, 4338132],
       [ 199998, 3935493],
       [ 199999, 3139021]], dtype=int32)

In [484]:
result = pd.DataFrame(result, columns = ["id", "price"])

In [485]:
result = result.astype(np.int32)

In [486]:
result

id    price
0      100000  6396485
1      100001  6166259
2      100002  2410517
3      100003  5984580
4      100004  6982645
...       ...      ...
99995  199995  4031920
99996  199996  5518228
99997  199997  4338132
99998  199998  3935493
99999  199999  3139021

[100000 rows x 2 columns]

In [487]:
result.to_csv("answer.csv", index = False)