<a href="https://colab.research.google.com/github/kiselpd/HW5_ML/blob/main/price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#for my GoogleDisk
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/GoogleColab/HW5

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/GoogleColab/HW5


In [2]:
%matplotlib inline
import pandas as pd
import numpy as np

In [3]:
train_df = pd.read_csv('Train.csv')
test_df = pd.read_csv('Test.csv')

In [4]:
import datetime as dt
train_df["date"] = pd.to_datetime(train_df["date"]).map(dt.datetime.toordinal)
test_df["date"] = pd.to_datetime(test_df["date"]).map(dt.datetime.toordinal)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
train_df = train_df.drop(columns = ["id"])
test_df = test_df.drop(columns = ["id"])

In [7]:
train_df.columns

Index(['date', 'street_id', 'build_tech', 'floor', 'area', 'rooms', 'balcon',
       'metro_dist', 'g_lift', 'n_photos', 'kw1', 'kw2', 'kw3', 'kw4', 'kw5',
       'kw6', 'kw7', 'kw8', 'kw9', 'kw10', 'kw11', 'kw12', 'kw13', 'price'],
      dtype='object')

In [8]:
X, y = train_test_split(train_df, test_size=0.33, random_state=42,  shuffle = False)

In [9]:
from sklearn.impute import KNNImputer

In [10]:
imputer = KNNImputer(n_neighbors = 50)
X = imputer.fit_transform(X)
y = imputer.fit_transform(y)

In [11]:
X = pd.DataFrame(X, columns = train_df.columns)
y = pd.DataFrame(y, columns = train_df.columns)

In [12]:
y_train = X["price"]
X_train = X.drop(columns = ["price"])

In [13]:
y_test = y["price"]
X_test = y.drop(columns = ["price"])

In [14]:
X_train

date  street_id  build_tech  floor  area  rooms  balcon  \
0      734138.0      560.0         0.6    2.0  59.0    3.0     0.0   
1      734138.0      667.0         1.1   10.0  50.0    2.0     1.0   
2      734138.0       90.0         0.0    1.0  48.0    2.0     0.0   
3      734138.0       94.0         1.0    3.0  62.0    3.0     1.0   
4      734138.0      232.0         0.0    3.0  60.0    3.0     0.0   
...         ...        ...         ...    ...   ...    ...     ...   
66995  734503.0      412.0         0.0    8.0  59.0    3.0     0.0   
66996  734503.0      438.0         0.0    1.0  34.0    1.0     0.0   
66997  734503.0      240.0         0.0   12.0  39.0    1.0     0.0   
66998  734503.0       25.0         1.0    3.0  35.0    1.0     0.0   
66999  734503.0        9.0         1.0    8.0  60.0    3.0     1.0   

       metro_dist  g_lift  n_photos  ...  kw4  kw5  kw6  kw7  kw8  kw9  kw10  \
0            30.0    1.00       5.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   0.0   
1            25.0    0.44       1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   0.0   
2            25.0    0.00       1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   0.0   
3            30.0    0.48       3.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   0.0   
4            25.0    0.54       3.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   0.0   
...           ...     ...       ...  ...  ...  ...  ...  ...  ...  ...   ...   
66995        10.0    1.00       2.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   0.0   
66996        15.0    1.00       0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   0.0   
66997        15.0    1.00       3.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   0.0   
66998         0.0    1.00       0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   0.0   
66999        30.0    0.00       0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   0.0   

       kw11  kw12  kw13  
0       0.0   0.0   0.0  
1       0.0   0.0   0.0  
2       0.0   0.0   0.0  
3       0.0   0.0   0.0  
4       0.0   0.0   0.0  
...     ...   ...   ...  
66995   0.0   0.0   0.0  
66996   0.0   0.0   0.0  
66997   0.0   0.0   0.0  
66998   0.0   0.0   0.0  
66999   0.0   0.0   0.0  

[67000 rows x 23 columns]

In [15]:
y_train

0         4510000.0
1        13231000.0
2         2008000.0
3        12680000.0
4         3335000.0
            ...    
66995     4275000.0
66996     2624000.0
66997     4682000.0
66998     3794000.0
66999    11049000.0
Name: price, Length: 67000, dtype: float64

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor

In [23]:
LR = LinearRegression()
LR.fit(X_train, y_train)

LR_pred = LR.predict(X_test)

In [24]:
LR_pred

array([ 5786407.62247038,  3470914.8137691 ,  5288326.43659997, ...,
        7171736.240448  , 27021755.53826118,  6274871.11817884])

In [25]:
KNN = KNeighborsRegressor()
KNN.fit(X_train, y_train)

KNN_pred = KNN.predict(X_test)

In [26]:
KNN_pred

array([ 3917000.,  3661000.,  6640000., ...,  4574600., 14909200.,
        5971600.])

In [27]:
X_train
print(y_train.ravel())
print(np.array(y_train))
print(np.array(X_train))

[ 4510000. 13231000.  2008000. ...  4682000.  3794000. 11049000.]
[ 4510000. 13231000.  2008000. ...  4682000.  3794000. 11049000.]
[[7.34138e+05 5.60000e+02 6.00000e-01 ... 0.00000e+00 0.00000e+00
  0.00000e+00]
 [7.34138e+05 6.67000e+02 1.10000e+00 ... 0.00000e+00 0.00000e+00
  0.00000e+00]
 [7.34138e+05 9.00000e+01 0.00000e+00 ... 0.00000e+00 0.00000e+00
  0.00000e+00]
 ...
 [7.34503e+05 2.40000e+02 0.00000e+00 ... 0.00000e+00 0.00000e+00
  0.00000e+00]
 [7.34503e+05 2.50000e+01 1.00000e+00 ... 0.00000e+00 0.00000e+00
  0.00000e+00]
 [7.34503e+05 9.00000e+00 1.00000e+00 ... 0.00000e+00 0.00000e+00
  0.00000e+00]]


In [37]:
RF = RandomForestRegressor(n_estimators = 100)
RF.fit(X_train, y_train.ravel())

RandomForestRegressor()

In [38]:
RF_pred = RF.predict(X_test)

In [39]:
RF_pred

array([ 7912030.,  3577760.,  9029410., ...,  7575590., 35519040.,
        6191620.])

In [40]:
stack = np.hstack([LR_pred.reshape(-1, 1), KNN_pred.reshape(-1, 1), RF_pred.reshape(-1, 1)])
stack

array([[ 5786407.62247038,  3917000.        ,  7912030.        ],
       [ 3470914.8137691 ,  3661000.        ,  3577760.        ],
       [ 5288326.43659997,  6640000.        ,  9029410.        ],
       ...,
       [ 7171736.240448  ,  4574600.        ,  7575590.        ],
       [27021755.53826118, 14909200.        , 35519040.        ],
       [ 6274871.11817884,  5971600.        ,  6191620.        ]])

In [36]:
y_test

0         9638000.0
1         2949000.0
2         4169000.0
3        13951000.0
4         5910000.0
            ...    
32995     1697000.0
32996     3620000.0
32997     6712000.0
32998    20835000.0
32999     2909000.0
Name: price, Length: 33000, dtype: float64

In [43]:
test_stack = np.hstack([X_test, stack])
test_stack

array([[7.34503000e+05, 6.65000000e+02, 1.00000000e+00, ...,
        5.78640762e+06, 3.91700000e+06, 7.91203000e+06],
       [7.34503000e+05, 1.29000000e+02, 0.00000000e+00, ...,
        3.47091481e+06, 3.66100000e+06, 3.57776000e+06],
       [7.34503000e+05, 2.20000000e+02, 1.00000000e+00, ...,
        5.28832644e+06, 6.64000000e+06, 9.02941000e+06],
       ...,
       [7.34563000e+05, 2.53000000e+02, 7.80000000e-01, ...,
        7.17173624e+06, 4.57460000e+06, 7.57559000e+06],
       [7.34563000e+05, 3.05000000e+02, 1.00000000e+00, ...,
        2.70217555e+07, 1.49092000e+07, 3.55190400e+07],
       [7.34563000e+05, 4.82000000e+02, 0.00000000e+00, ...,
        6.27487112e+06, 5.97160000e+06, 6.19162000e+06]])

In [44]:
RF = RandomForestRegressor(n_estimators = 100)
RF.fit(test_stack, y_test.ravel())

RandomForestRegressor()