<a href="https://colab.research.google.com/github/kiselpd/HW5_ML/blob/main/price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#for my GoogleDisk
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/GoogleColab/HW5

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/GoogleColab/HW5


In [611]:
%matplotlib inline
import pandas as pd
import numpy as np

In [612]:
train_df = pd.read_csv('Train.csv')
test_df = pd.read_csv('Test.csv')

In [613]:
import datetime as dt
train_df["date"] = pd.to_datetime(train_df["date"]).map(dt.datetime.toordinal)
test_df["date"] = pd.to_datetime(test_df["date"]).map(dt.datetime.toordinal)

In [614]:
from sklearn.model_selection import train_test_split

In [615]:
id = test_df["id"]
id

0        100000
1        100001
2        100002
3        100003
4        100004
          ...  
99995    199995
99996    199996
99997    199997
99998    199998
99999    199999
Name: id, Length: 100000, dtype: int64

In [616]:
train_df = train_df.drop(columns = ["id"])
test_df = test_df.drop(columns = ["id"])

In [617]:
X, y = train_test_split(train_df, test_size=0.2, random_state=42)

In [618]:
from sklearn.impute import KNNImputer

In [619]:
X = X.fillna(0)
y = y.fillna(0)

In [620]:
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [621]:
X = pd.DataFrame(X, columns = train_df.columns)
y = pd.DataFrame(y, columns = train_df.columns)

In [622]:
X

date  street_id  build_tech  floor  area  rooms  balcon  metro_dist  \
75220  734777         94         2.0      8    88      3       2        20.0   
48955  734289        530         0.0      9    61      3       0        20.0   
44966  734289         92         0.0      7    58      2       0        30.0   
13568  734442        637         0.0      3    53      2       1        30.0   
92727  734534        195         0.0      3    41      2       0        20.0   
...       ...        ...         ...    ...   ...    ...     ...         ...   
6265   734411        259         1.0      5    60      3       1        30.0   
54886  734319        283         1.0     10    60      3       1        20.0   
76820  734777         18         1.0      2    60      3       1        30.0   
860    734138        283         1.0      1    60      3       0        25.0   
15795  734442        517         0.0      6    34      1       0        10.0   

       g_lift  n_photos  kw1  kw2  kw3  kw4  kw5  kw6  kw7  kw8  kw9  kw10  \
75220     1.0         4    0    0    0    0    0    0    0    0    0     0   
48955     0.0         5    0    0    0    0    0    0    0    0    0     0   
44966     0.0         4    1    1    0    0    0    0    0    0    0     0   
13568     0.0         3    0    0    0    0    0    0    0    0    0     0   
92727     0.0         0    0    0    0    0    0    0    0    0    0     0   
...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
6265      0.0         7    0    1    0    0    0    0    0    0    0     0   
54886     0.0         4    0    1    0    0    0    0    0    0    0     0   
76820     1.0         3    0    1    0    0    0    0    0    0    0     0   
860       1.0         0    0    0    0    0    0    0    0    0    0     0   
15795     0.0         0    0    0    0    0    0    0    0    0    0     0   

       kw11  kw12  kw13     price  
75220     0     0     0  45313000  
48955     0     0     0   6052000  
44966     0     0     0   3855000  
13568     0     0     0   2801000  
92727     0     0     0   5655000  
...     ...   ...   ...       ...  
6265      0     0     0   5023000  
54886     0     0     0   5636000  
76820     0     0     0   2957000  
860       0     0     0   4913000  
15795     0     0     0   5330000  

[80000 rows x 24 columns]

In [623]:
y_train = X["price"]
X_train = X.drop(columns = ["price"])

In [624]:
y_test = y["price"]
X_test = y.drop(columns = ["price"])

In [625]:
X_train

date  street_id  build_tech  floor  area  rooms  balcon  metro_dist  \
75220  734777         94         2.0      8    88      3       2        20.0   
48955  734289        530         0.0      9    61      3       0        20.0   
44966  734289         92         0.0      7    58      2       0        30.0   
13568  734442        637         0.0      3    53      2       1        30.0   
92727  734534        195         0.0      3    41      2       0        20.0   
...       ...        ...         ...    ...   ...    ...     ...         ...   
6265   734411        259         1.0      5    60      3       1        30.0   
54886  734319        283         1.0     10    60      3       1        20.0   
76820  734777         18         1.0      2    60      3       1        30.0   
860    734138        283         1.0      1    60      3       0        25.0   
15795  734442        517         0.0      6    34      1       0        10.0   

       g_lift  n_photos  kw1  kw2  kw3  kw4  kw5  kw6  kw7  kw8  kw9  kw10  \
75220     1.0         4    0    0    0    0    0    0    0    0    0     0   
48955     0.0         5    0    0    0    0    0    0    0    0    0     0   
44966     0.0         4    1    1    0    0    0    0    0    0    0     0   
13568     0.0         3    0    0    0    0    0    0    0    0    0     0   
92727     0.0         0    0    0    0    0    0    0    0    0    0     0   
...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
6265      0.0         7    0    1    0    0    0    0    0    0    0     0   
54886     0.0         4    0    1    0    0    0    0    0    0    0     0   
76820     1.0         3    0    1    0    0    0    0    0    0    0     0   
860       1.0         0    0    0    0    0    0    0    0    0    0     0   
15795     0.0         0    0    0    0    0    0    0    0    0    0     0   

       kw11  kw12  kw13  
75220     0     0     0  
48955     0     0     0  
44966     0     0     0  
13568     0     0     0  
92727     0     0     0  
...     ...   ...   ...  
6265      0     0     0  
54886     0     0     0  
76820     0     0     0  
860       0     0     0  
15795     0     0     0  

[80000 rows x 23 columns]

In [626]:
y_train

75220    45313000
48955     6052000
44966     3855000
13568     2801000
92727     5655000
           ...   
6265      5023000
54886     5636000
76820     2957000
860       4913000
15795     5330000
Name: price, Length: 80000, dtype: int64

In [627]:
X_train

date  street_id  build_tech  floor  area  rooms  balcon  metro_dist  \
75220  734777         94         2.0      8    88      3       2        20.0   
48955  734289        530         0.0      9    61      3       0        20.0   
44966  734289         92         0.0      7    58      2       0        30.0   
13568  734442        637         0.0      3    53      2       1        30.0   
92727  734534        195         0.0      3    41      2       0        20.0   
...       ...        ...         ...    ...   ...    ...     ...         ...   
6265   734411        259         1.0      5    60      3       1        30.0   
54886  734319        283         1.0     10    60      3       1        20.0   
76820  734777         18         1.0      2    60      3       1        30.0   
860    734138        283         1.0      1    60      3       0        25.0   
15795  734442        517         0.0      6    34      1       0        10.0   

       g_lift  n_photos  kw1  kw2  kw3  kw4  kw5  kw6  kw7  kw8  kw9  kw10  \
75220     1.0         4    0    0    0    0    0    0    0    0    0     0   
48955     0.0         5    0    0    0    0    0    0    0    0    0     0   
44966     0.0         4    1    1    0    0    0    0    0    0    0     0   
13568     0.0         3    0    0    0    0    0    0    0    0    0     0   
92727     0.0         0    0    0    0    0    0    0    0    0    0     0   
...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
6265      0.0         7    0    1    0    0    0    0    0    0    0     0   
54886     0.0         4    0    1    0    0    0    0    0    0    0     0   
76820     1.0         3    0    1    0    0    0    0    0    0    0     0   
860       1.0         0    0    0    0    0    0    0    0    0    0     0   
15795     0.0         0    0    0    0    0    0    0    0    0    0     0   

       kw11  kw12  kw13  
75220     0     0     0  
48955     0     0     0  
44966     0     0     0  
13568     0     0     0  
92727     0     0     0  
...     ...   ...   ...  
6265      0     0     0  
54886     0     0     0  
76820     0     0     0  
860       0     0     0  
15795     0     0     0  

[80000 rows x 23 columns]

In [628]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor

In [629]:
RFR = RandomForestRegressor(n_estimators = 200, min_samples_split = 4)
RFR.fit(X_train, y_train)

RFR_pred = RFR.predict(X_test)

In [630]:
mean_absolute_error(y_test, RFR_pred)

1674012.4540832902

In [631]:
LiR = LinearRegression()
LiR.fit(X_train, y_train)

LiR_pred = LiR.predict(X_test)

In [632]:
LiR_pred

array([6356043.50253868, 3680700.08362269, 4112165.41212177, ...,
       5321934.45324731, 5108796.98157668, 5460623.25077462])

In [633]:
mean_absolute_error(y_test, LiR_pred)

1832026.287952391

In [634]:
GBR = GradientBoostingRegressor()
GBR.fit(X_train, y_train.ravel())

GBR_pred = GBR.predict(X_test)

In [635]:
GBR_pred

array([5086819.37064911, 3093162.30146592, 3646691.46367647, ...,
       5876964.79290519, 4782311.6545548 , 5050705.67750208])

In [636]:
mean_absolute_error(y_test, GBR_pred)

1720859.8966942234

In [637]:
RD = Ridge()
RD.fit(X_train, y_train.ravel())

RD_pred = RD.predict(X_test)

In [638]:
RD_pred

array([6356030.13394713, 3680637.29787064, 4112098.6076231 , ...,
       5321952.91176033, 5108783.21694422, 5460740.14450741])

In [639]:
mean_absolute_error(y_test, RD_pred)

1832026.8779113633

In [586]:
L = Lasso()
L.fit(X_train, y_train.ravel())

L_pred = L.predict(X_test)

In [587]:
L_pred

array([6207021.37887812, 3582111.99977708, 4384063.15590501, ...,
       5137547.56014705, 3346838.82221437, 4682534.12887216])

In [588]:
mean_absolute_error(y_test, L_pred)

1846784.211883427

In [640]:
stack = np.hstack([GBR_pred.reshape(-1, 1), LiR_pred.reshape(-1, 1), RD_pred.reshape(-1, 1), RFR_pred.reshape(-1, 1)])
stack

array([[5086819.37064911, 6356043.50253868, 6356030.13394713,
        5638755.51190476],
       [3093162.30146592, 3680700.08362269, 3680637.29787064,
        2794211.47420635],
       [3646691.46367647, 4112165.41212177, 4112098.6076231 ,
        3606374.90079365],
       ...,
       [5876964.79290519, 5321934.45324731, 5321952.91176033,
        5806922.88690476],
       [4782311.6545548 , 5108796.98157668, 5108783.21694422,
        4189314.56547619],
       [5050705.67750208, 5460623.25077462, 5460740.14450741,
        4663529.73214286]])

In [641]:
y_test

75721    5651000
80184    1321000
19864    2250000
76699    2539000
92991    2396000
          ...   
32595    8373000
29313    5017000
37862    9879000
53421    2287000
42410    4965000
Name: price, Length: 20000, dtype: int64

In [642]:
test_stack = np.hstack([X_test, stack])
test_stack

array([[7.34777000e+05, 3.45000000e+02, 1.00000000e+00, ...,
        6.35604350e+06, 6.35603013e+06, 5.63875551e+06],
       [7.34808000e+05, 3.97000000e+02, 0.00000000e+00, ...,
        3.68070008e+06, 3.68063730e+06, 2.79421147e+06],
       [7.34472000e+05, 5.88000000e+02, 0.00000000e+00, ...,
        4.11216541e+06, 4.11209861e+06, 3.60637490e+06],
       ...,
       [7.34228000e+05, 6.65000000e+02, 1.00000000e+00, ...,
        5.32193445e+06, 5.32195291e+06, 5.80692289e+06],
       [7.34319000e+05, 5.25000000e+02, 0.00000000e+00, ...,
        5.10879698e+06, 5.10878322e+06, 4.18931457e+06],
       [7.34258000e+05, 5.02000000e+02, 0.00000000e+00, ...,
        5.46062325e+06, 5.46074014e+06, 4.66352973e+06]])

In [ ]:
#GBR = GradientBoostingRegressor()
#BR.fit(X_train, y_train.ravel())

#GBR_pred = GBR.predict(X_test)

In [643]:
GBR_stack = GradientBoostingRegressor(n_estimators = 100)
GBR_stack.fit(test_stack, y_test.ravel())

GradientBoostingRegressor()

In [644]:
test_df

date  street_id  build_tech  floor  area  rooms  balcon  metro_dist  \
0      734563        459         NaN      1    60      3       1        30.0   
1      734563        344         1.0     10    52      2       1         NaN   
2      734563        585         0.0      4    54      3       0        30.0   
3      734563        494         NaN      2    52      2       1        25.0   
4      734563        622         1.0      9    60      3       1        15.0   
...       ...        ...         ...    ...   ...    ...     ...         ...   
99995  735112        613         1.0      2    34      1       1        25.0   
99996  735112        167         1.0     10    61      3       1        30.0   
99997  735112        391         1.0      9    34      1       1        30.0   
99998  735112         21         0.0      7    58      3       0        30.0   
99999  735112        409         0.0     11    33      1       0         NaN   

       g_lift  n_photos  kw1  kw2  kw3  kw4  kw5  kw6  kw7  kw8  kw9  kw10  \
0         0.0         4    0    0    0    0    0    0    0    0    0     0   
1         NaN         4    0    0    0    0    0    0    0    0    0     0   
2         0.0         0    0    0    0    0    0    0    0    0    0     0   
3         1.0         3    0    1    0    0    0    0    0    0    0     0   
4         NaN         1    1    1    0    0    0    0    0    0    0     0   
...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
99995     NaN         2    0    1    0    0    0    0    0    0    0     0   
99996     NaN         4    0    1    0    0    0    0    0    0    0     0   
99997     NaN         3    0    1    0    0    0    0    0    0    0     0   
99998     0.0         3    0    0    0    0    0    0    0    0    0     0   
99999     0.0         1    0    0    0    0    0    0    0    0    0     0   

       kw11  kw12  kw13  
0         0     0     0  
1         0     0     0  
2         0     0     0  
3         0     0     0  
4         0     0     0  
...     ...   ...   ...  
99995     0     0     0  
99996     0     0     0  
99997     0     0     0  
99998     0     0     0  
99999     0     0     0  

[100000 rows x 23 columns]

In [645]:
test_df = test_df.fillna(0)


In [646]:
test_df

date  street_id  build_tech  floor  area  rooms  balcon  metro_dist  \
0      734563        459         0.0      1    60      3       1        30.0   
1      734563        344         1.0     10    52      2       1         0.0   
2      734563        585         0.0      4    54      3       0        30.0   
3      734563        494         0.0      2    52      2       1        25.0   
4      734563        622         1.0      9    60      3       1        15.0   
...       ...        ...         ...    ...   ...    ...     ...         ...   
99995  735112        613         1.0      2    34      1       1        25.0   
99996  735112        167         1.0     10    61      3       1        30.0   
99997  735112        391         1.0      9    34      1       1        30.0   
99998  735112         21         0.0      7    58      3       0        30.0   
99999  735112        409         0.0     11    33      1       0         0.0   

       g_lift  n_photos  kw1  kw2  kw3  kw4  kw5  kw6  kw7  kw8  kw9  kw10  \
0         0.0         4    0    0    0    0    0    0    0    0    0     0   
1         0.0         4    0    0    0    0    0    0    0    0    0     0   
2         0.0         0    0    0    0    0    0    0    0    0    0     0   
3         1.0         3    0    1    0    0    0    0    0    0    0     0   
4         0.0         1    1    1    0    0    0    0    0    0    0     0   
...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
99995     0.0         2    0    1    0    0    0    0    0    0    0     0   
99996     0.0         4    0    1    0    0    0    0    0    0    0     0   
99997     0.0         3    0    1    0    0    0    0    0    0    0     0   
99998     0.0         3    0    0    0    0    0    0    0    0    0     0   
99999     0.0         1    0    0    0    0    0    0    0    0    0     0   

       kw11  kw12  kw13  
0         0     0     0  
1         0     0     0  
2         0     0     0  
3         0     0     0  
4         0     0     0  
...     ...   ...   ...  
99995     0     0     0  
99996     0     0     0  
99997     0     0     0  
99998     0     0     0  
99999     0     0     0  

[100000 rows x 23 columns]

In [647]:
GBR_test_pred = GBR.predict(test_df)

In [648]:
LiR_test_pred = LiR.predict(test_df)

In [598]:
L_test_pred = L.predict(test_df)

In [649]:
RD_test_pred = RD.predict(test_df)

In [650]:
RFR_test_pred = RFR.predict(test_df)

In [651]:
test_stack = np.hstack([test_df, GBR_test_pred.reshape(-1, 1), LiR_test_pred.reshape(-1, 1), RD_test_pred.reshape(-1, 1), RFR_test_pred.reshape(-1, 1)])
test_stack.shape

(100000, 27)

In [652]:
final_pred = GBR_stack.predict(test_stack)

In [653]:
final_pred

array([5909265.78361927, 7549437.73310665, 3027246.30522169, ...,
       3960882.24820099, 3781294.29787299, 3191609.26026416])

In [654]:
result = np.hstack([(id.to_numpy()).reshape(-1, 1), final_pred.reshape(-1, 1)])

In [655]:
result.astype(np.int32)

array([[ 100000, 5909265],
       [ 100001, 7549437],
       [ 100002, 3027246],
       ...,
       [ 199997, 3960882],
       [ 199998, 3781294],
       [ 199999, 3191609]], dtype=int32)

In [656]:
result = pd.DataFrame(result, columns = ["id", "price"])

In [657]:
result = result.astype(np.int32)

In [658]:
result

id    price
0      100000  5909265
1      100001  7549437
2      100002  3027246
3      100003  4919377
4      100004  7025133
...       ...      ...
99995  199995  3879416
99996  199996  5590967
99997  199997  3960882
99998  199998  3781294
99999  199999  3191609

[100000 rows x 2 columns]

In [659]:
result.to_csv("answer.csv", index = False)